version: '3'
services:
  fflogs-send-discord:
    container_name: fflogs-send-discord
    env_file: .env
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./lib:/var/app/lib
